<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="PC-20190714VZJO" name="com.course.testng.TimeOutTest" tests="2" failures="0" timestamp="23 一月 2021 08:25:03 GMT" time="4.030" errors="1">
  <testcase name="test1" time="2.028" classname="com.course.testng.TimeOutTest"/>
  <testcase name="test2" time="2.002" classname="com.course.testng.TimeOutTest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.course.testng.TimeOutTest.test2() didn&#039;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.course.testng.TimeOutTest.test2() didn't finish within the time-out 2000]]>
    </error>
  </testcase> <!-- test2 -->
</testsuite> <!-- com.course.testng.TimeOutTest -->
