<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC-20190714VZJO" ignored="0" name="LearnGit" tests="2" failures="1" timestamp="23 一月 2021 08:25:03 GMT" time="4.11" errors="0">
  <testcase name="test1" time="2.028" classname="com.course.testng.TimeOutTest"/>
  <testcase name="test2" time="2.002" classname="com.course.testng.TimeOutTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.course.testng.TimeOutTest.test2() didn&amp;apos;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.course.testng.TimeOutTest.test2() didn't finish within the time-out 2000]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- LearnGit -->
